const FETCH_USER_REQUEST = 'FETCH_USER_REQUEST';
const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS';
const FETCH_USER_FAILUR = 'FETCH_USER_FAILUR';
export { FETCH_USER_REQUEST,FETCH_USER_SUCCESS,FETCH_USER_FAILUR } ;