const FETCH_INSTANCE_REQUEST = 'FETCH_INSTANCE_REQUEST';
const FETCH_INSTANCE_SUCCESS = 'FETCH_INSTANCE_SUCCESS';
const FETCH_INSTANCE_FAILUR = 'FETCH_INSTANCE_FAILUR';
export { FETCH_INSTANCE_REQUEST,FETCH_INSTANCE_SUCCESS,FETCH_INSTANCE_FAILUR } ;